name: spotify-mpd-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - altair
  - streamlit
  - jupyter
  - ipython
  - spotipy
  - implicit
  - lightfm
  - tqdm
  - pip
  - pip:
      - seaborn
      - umap-learn
